Add passed with warnings for pylint

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -28,11 +28,25 @@ jobs:
       run: |
         find suprb/ -name "*.py" -print0 | xargs -0 -n 1 -P 4 pylint --max-line-length=120 --output-format=text > pylint-report.txt || true
 
-    - name: Check for warnings in pylint report
+    - name: Check for warnings in Pylint report
+      id: lint-check
       run: |
-          if grep -q 'Your code has been rated at' pylint-report.txt; then
-            echo "Pylint completed with warnings. Review the pylint report for details."
+          if grep -q "rated at" pylint-report.txt; then
+            if grep -q "Your code has been rated at 10.00/10" pylint-report.txt; then
+              echo "status=success" >> $GITHUB_ENV
+              echo "No warnings or errors found."
+            else
+              echo "status=warning" >> $GITHUB_ENV
+              echo "Linting passed with warnings. Review the report."
+            fi
+          else
+            echo "status=failure" >> $GITHUB_ENV
+            echo "No linting output found. Please check the configuration."
+            exit 1
           fi
+      
+    - name: Output Pylint status
+      run: echo "Pylint Status: ${{ env.status }}"
 
     - name: Upload pylint report
       uses: actions/upload-artifact@v3
